name: Python Application Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3

    - name: 1. Creating virtual env
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: 2. Installing dependencies
      run: |
        pip install gym
        pip install -r requirements.txt
        pip install gdown  # ⬅️ 加這行來安裝 gdown

    - name: 4. Download weights.pkl from Google Drive
      run: |
        gdown --fuzzy 'https://drive.google.com/file/d/1OolRvfUON-Fmfo6AJu09PnY1KNt3s2CI/view?usp=share_link' #stage 1
        gdown --fuzzy 'https://drive.google.com/file/d/1l1OV3CvhnoGjlgfOQvfzuyLsYfFUedXb/view?usp=share_link' #stage 3
        gdown --fuzzy 'https://drive.google.com/file/d/163zW-1CTB2HhzgZY_rVRszwhD0HIQs5m/view?usp=sharing' #stage 2
        gdown --fuzzy 'https://drive.google.com/file/d/1yoUM2FqHfGuJbSS9BYmRh4vnWCajXW35/view?usp=sharing' #stage 4
        gdown --fuzzy 'https://drive.google.com/file/d/1N_XEXrEue4njN_zWhLuM3EhUOkUX0nTM/view?usp=share_link' #stage 5
        gdown --fuzzy 'https://drive.google.com/file/d/1JOWB6pdmMgVBaku-xhp0c41cAJxT5gUy/view?usp=sharing' #stage 6
        gdown --fuzzy 'https://drive.google.com/file/d/10KG5sCfGew9xlYvj0mQr8UnXLW66Z3P8/view?usp=sharing' #stage 7
        gdown --fuzzy 'https://drive.google.com/file/d/1WAFAxCba5xpBYrkZIZDUW-Iin9XIYrIv/view?usp=sharing' #stage 8

    - name: 5. Ensure env.so is executable
      run: chmod +x env.cpython-38-x86_64-linux-gnu.so

    - name: 6. Run Evaluation
      run: python eval.py --token a91aae52cff9ef65932db06b150ffd47
