name: Python Application Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3

    - name: 1. Creating virtual env
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: 2. Installing dependencies
      run: |
        pip install gym
        pip install -r requirements.txt
        pip install gdown  # ⬅️ 加這行來安裝 gdown

    - name: 4. Download weights.pkl from Google Drive
      run: |
        gdown --fuzzy 'https://drive.google.com/file/d/11JDiuFvkiRemfXIG1LX_uTViF9YezAaS/view?usp=share_link' #stage 1
        gdown --fuzzy 'https://drive.google.com/file/d/1XSQD3_G6TP6WYfpJuOuLeHrFzJHjhJo-/view?usp=share_link' #stage 2
        gdown --fuzzy 'https://drive.google.com/file/d/1b5RW1a-jrZFt3THi4JiXD7b6yJYWEN9L/view?usp=share_link' #stage 3

    - name: 5. Ensure env.so is executable
      run: chmod +x env.cpython-38-x86_64-linux-gnu.so

    - name: 6. Run Evaluation
      run: python eval.py --token a91aae52cff9ef65932db06b150ffd47
